name: Helm Chart Version Increment and Package

on:
  push:
    branches:
      - main # or your main branch name

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Increment version (semantic)
        id: increment_version 
        run: |
          yq eval '.version = '"${{ steps.version.outputs.version }}"'' Chart.yaml > Chart.yaml.tmp && mv Chart.yaml.tmp Chart.yaml

      - name: Commit version change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated version bump to ${{ steps.version.outputs.version }}'
          file_pattern: Chart.yaml
          push_options: '--force-with-lease'

      - name: Package Helm chart
        run: helm package .

      - name: Upload Helm chart artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: ./*.tgz
      
      - name: Tag branch
        run: |
          git tag v${{ steps.version.outputs.version }}
          git push origin  v${{ steps.version.outputs.version }}
      

      #- name: Publish Helm chart to a repository (optional)
      #  if: startsWith(github.ref, 'refs/tags/') # Only publish on tag creation (after a release)
      #  run: |
      #    helm repo add my-repo <your_helm_repo_url> # replace with your helm repo
      #    helm repo update
      #    helm push my-chart-*.tgz my-repo
      #  env:
      #    # Add your Helm repository credentials as secrets:
      #    HELM_USERNAME: ${{ secrets.HELM_USERNAME }}
      #    HELM_PASSWORD: ${{ secrets.HELM_PASSWORD }}
